### ISSUE TITLE
Fix slather in Travis CI

### ISSUE THREAD

**Issue by guidomb** [Wolox/WLXBluetoothDevice#25]
```
$ bundle exec slather

Slathering...

/Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/slather-1.6.0/lib/slather/project.rb:49:in `coverage_files': No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj` (StandardError)

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/slather-1.6.0/lib/slather/coverage_service/coveralls.rb:44:in `coveralls_coverage_data'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/slather-1.6.0/lib/slather/coverage_service/coveralls.rb:84:in `post'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/slather-1.6.0/bin/slather:67:in `post'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/slather-1.6.0/bin/slather:37:in `execute'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.4/lib/clamp/command.rb:67:in `run'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.4/lib/clamp/subcommand/execution.rb:11:in `execute'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.4/lib/clamp/command.rb:67:in `run'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.4/lib/clamp/command.rb:132:in `run'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.4/lib/clamp.rb:6:in `Clamp'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/gems/slather-1.6.0/bin/slather:6:in `<top (required)>'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/bin/slather:23:in `load'

from /Users/travis/build/Wolox/WLXBluetoothDevice/vendor/bundle/ruby/2.1.0/bin/slather:23:in `<main>'
```

**Comment by guidomb** [comment]
I disable slather when I refactored the project to support Carthage.

**Comment by guidomb** [comment]
We can also try https://github.com/macmade/xcode-coveralls
